import useLogs from "../hooks/useLogs";
import LogsTable from "../components/LogsTable";
import DashboardStats from "../components/DashboardStats";

function AdminDashboard() {
  const { logs, loading } = useLogs();

  return (
    <div className="container">

      <h1>Refund Dashboard</h1>

      <p>Live refund decisions generated by the AI agent.</p>

      {!loading && <DashboardStats logs={logs} />}

      {loading ? (
        <h3>Loading...</h3>
      ) : (
        <LogsTable logs={logs} />
      )}

    </div>
  );
}

export default AdminDashboard;